### ISSUE TITLE
baselineContextSSL not initializing SSL

### ISSUE THREAD

**Issue by narrative** [afcowie/http-streams#104]
Hi there,

Running this example code taken from the documentation:
```haskell
main :: IO ()
main = do
  ctx <- baselineContextSSL
  c <- openConnectionSSL ctx "api.github.com" 443
  closeConnection c
```

And receiving the following exception:
```
Main> main
*** Exception: user error (error:140A90A1:lib(20):func(169):reason(161))
```

Googling the error code turned up the following:
```
$ openssl errstr 0x140A90A1
error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers
```

From further googling, this error message indicates the SSL library is not being initialized properly.

I noted that your documentation states the following:

> There is no longer a need to call withOpenSSL explicitly; the initialization is invoked once per process for you

However, when I changed my code to the following:

```haskell
main :: IO ()
main = withOpenSSL $ do
  ctx <- baselineContextSSL
  c <- openConnectionSSL ctx "api.github.com" 443
  closeConnection c
```

The exception was no longer being thrown. I see from the source code that `openConnectionSSL` is wrapped in a `withOpenSSL`, however perhaps `baselineContextSSL` could also be wrapped to prevent this? If this is the desired behavior, perhaps the documentation can be cleared up?

Thanks

**Comment by afcowie** [comment]
Yeah, it makes sense to guard the case where `baselineContextSSL` is called directly first. It should all Just Work™.

**Comment by afcowie** [comment]
@narrative have a look at https://github.com/afcowie/http-streams/commit/a658850c02be81e75603865bf248d1230fbe77dc and let me know whether that covers it off for you?

**Comment by narrative** [comment]
That should do it. Much appreciated.
