### ISSUE TITLE
release 0.7.2.5 doesn't include test modules

### ISSUE THREAD

**Issue by aycanirican** [afcowie/http-streams#80]
```
In-place registering http-streams-0.7.2.5...
Preprocessing test suite 'check' for http-streams-0.7.2.5...

tests/check.hs:19:8:
    Could not find module ‘MockServer’
    Use -v to see a list of the files searched for.

tests/check.hs:20:8:
    Could not find module ‘TestSuite’
    Use -v to see a list of the files searched for.
```

**Comment by afcowie** [comment]
How did you get that? `make test` worked here...

**Comment by aycanirican** [comment]
hackage release doesn't include MockServer, see: http://hackage.haskell.org/package/http-streams-0.7.2.5/src/tests/

**Comment by trofi** [comment]
Still encountering the issue.

Step by step instructions to reproduce on current git trees:
```
# fetch sources
$ git clone git://github.com/afcowie/http-common
$ git clone git://github.com/afcowie/http-streams

# make fresh tarballs, those which to-be-appeared on hackage
$ ( cd http-common/; cabal sdist )
$ ( cd http-streams/; cabal sdist )

# unpack stuff
$ tar -xzf http-common/dist/http-common-0.8.0.1.tar.gz
$ tar -xzf http-streams/dist/http-streams-0.8.0.2.tar.gz

# finally build stuff (note versioned dirs from sdist, not a git tree)
$ cabal sandbox init
$ cabal install http-common-0.8.0.1/ http-streams-0.8.0.2/ --enable-tests

In-place registering http-streams-0.8.0.2...
Preprocessing test suite 'check' for http-streams-0.8.0.2...

tests/check.hs:19:8:
    Could not find module ‘MockServer’
    Use -v to see a list of the files searched for.

tests/check.hs:20:8:
    Could not find module ‘TestSuite’
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
http-streams-0.8.0.2 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by afcowie** [comment]
Ok. Policy question, then. Should the hackage release include the test code, or just the library? The _source_ tree includes the test code, obviously, and I'm always in a checkout when I run the tests. In my experience one doesn't bundle test code into release artifacts, but maybe I'm missing something?   cc @gregorycollins @hvr

**Comment by gregorycollins** [comment]
Usually hackage releases include tests.

**Comment by snoyberg** [comment]
Just saw this with a Stackage build too:

```
tests/check.hs:19:8:
    Could not find module ‘MockServer’
    Use -v to see a list of the files searched for.

tests/check.hs:20:8:
    Could not find module ‘TestSuite’
    Use -v to see a list of the files searched for.
```

**Comment by afcowie** [comment]
I'm really a bit vague about this. If people want test code in the generated package, then the cabal tooling should include it; having to list source files by name in extra files or whatever seems ridiculous when the module names are already listed in the test-suite sections.

**Comment by snoyberg** [comment]
You would need to add modules like `TestSuite` to the `other-modules` field of the test suite stanza. Right now, cabal doesn't know anything about them (because it would have to actually perform a build and query GHC to discover that information, which it doesn't do).

**Comment by hvr** [comment]
@snoyberg ...and even if it did, it would have to inspect all CPP branches in case some modules are imported conditionally =)

**Comment by afcowie** [comment]
Ok. I've bowed to peer pressure. I'll upload 0.8.3.2 momentarily.

**Comment by afcowie** [comment]
@snoyberg can you let me know if stackage isn't happy?

**Comment by snoyberg** [comment]
I'll let you know
