### ISSUE TITLE
Allow override of User-Agent

### ISSUE THREAD

**Issue by afcowie** [afcowie/http-streams#83]
Because, y'know, the web is a better place for the existence of sites that key their responses based on this strongly typed header field. @mwotton

**Comment by hvr** [comment]
wait... what happens currently if I `setHeader "User-Agent" "foo/0.1"`? :confused:

**Comment by afcowie** [comment]
@hvr Ah. Hm. You're right. We _used_ to set the `User-Agent`, then someone asked us to stop. So yes, that will work.
