### ISSUE TITLE
http-streams-0.7.2.6 does not compile with GHC 7.8.4

### ISSUE THREAD

**Issue by peti** [afcowie/http-streams#85]
A complete build log that shows the error is available at http://hydra.cryp.to/build/730616/nixlog/1/raw. My guess is that some API change in blaze triggered the issue.

**Comment by afcowie** [comment]
Thanks. I'll have a look.

**Comment by aycanirican** [comment]
+1

**Comment by afcowie** [comment]
I just did a clean sandbox build, GHC 7.8.4 latest Hackage tree; `make test` built all the way and tests passed. Not sure what to contribute from here?

**Comment by ttuegel** [comment]
It's nothing to do with GHC 7.8.4, it's the upgrade to io-streams-1.3.0.0.

**Comment by afcowie** [comment]
Ah, sorry. Ok. I'll force that and see what I hit.

**Comment by ttuegel** [comment]
@peti It's fixed with `blaze-builder >= 4`. `blaze-builder < 4` used a custom `Builder` type, not the one provided by `bytestring`.

**Comment by afcowie** [comment]
@ttuegel so should I be requiring `io-streams >= 1.3`, or `blaze-builder >= 0.4`, or leaving it to the consumer of the library? [the sandbox build I did brought both of those in, explaining why I didn't have a problem]

**Comment by ttuegel** [comment]
@afcowie You need both `io-streams >= 1.3` and `blaze-builder >= 0.4`. The newer blaze-builder isn't compatible with older io-streams versions, but the older blaze-builder isn't compatible with newer io-streams versions. So the upper bounds `io-streams < 1.3, blaze-builder < 0.4` would work, but I don't think that's what anyone wants! :)

**Comment by eyeinsky** [comment]
created a pull request #86

**Comment by afcowie** [comment]
Closed via #86

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by afcowie** [comment]
It's already been uploaded; v0.8.3.1
