### ISSUE TITLE
POST body content prefixed by size.

### ISSUE THREAD

**Issue by noteed** [afcowie/http-streams#94]
I'm observing the request sent by `http-streams` with `nc`:

```
> nc -n -l 0.0.0.0 8000
POST / HTTP/1.1
Host: 127.0.0.1:8000
Accept-Encoding: gzip
Transfer-Encoding: chunked
Content-Type: plain/text
Accept: */*

0006
Hello

```

(Kill `nc` with Ctrl-C.)

Notice how `Hello` is prefixed by `0006\n`.

Running

```
curl -s -X POST --data-binary "hello" http://127.0.0.1:8000
```

will not result in a size prefix.

Sample program:

```
main = do
  x <- post "http://127.0.0.1:8000"
    "plain/text"
    (\os -> do
      Streams.write (Just $ byteString "Hello\n") os
      Streams.write Nothing os)
    concatHandler
  print x
```

For information, this program produces the expected result:

```
main = do
  os <- Streams.builderStream Streams.stdout
  Streams.write (Just $ byteString "Hello\n") os
  Streams.write Nothing os
```

This is with GHC 7.8.4, http-streams-0.8.3.3 and io-streams-1.3.2.0.

**Comment by noteed** [comment]
Oh I see it's chunked...

**Comment by afcowie** [comment]
You can control it with https://hackage.haskell.org/package/http-streams-0.8.3.3/docs/Network-Http-Client.html#v:setTransferEncoding (or more to the point, setContentLength). Hopefully that gives you what you need. But thanks for a very thorough bug report. Cheers!
